# home-manager の initContent として読み込まれる zsh 設定。
# キーマップ・履歴・補完の初期化 (compinit) は home-manager 側 (zsh.nix) で行う。

# 単語の区切り文字を指定する
autoload -Uz select-word-style
select-word-style default
# ここで指定した文字は単語区切りとみなされる
# / も区切りと扱うので、^W でディレクトリ１つ分を削除できる
zstyle ':zle:*' word-chars " /=;@:{},|"
zstyle ':zle:*' word-style unspecified

########################################
# 補完

# Shift + TABで補完を逆に辿れるようにする
zmodload zsh/complist
bindkey -M menuselect '^[[Z' reverse-menu-complete

# ファイル補完候補に色を付ける
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# セパレータを設定する
zstyle ':completion:*' list-separator '-->'
zstyle ':completion:*:manuals' separate-sections true

# 選択している補完をハイライトする
zstyle ':completion:*' menu select

# 補完で小文字でも大文字にマッチさせる
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# ../ の後は今いるディレクトリを補完しない
zstyle ':completion:*' ignore-parents parent pwd ..

# sudo の後ろでコマンド名を補完する
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin \
                   /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin

# ps コマンドのプロセス名補完
zstyle ':completion:*:processes' command 'ps x -o pid,s,args'

# 補完関数の表示を強化する
zstyle ':completion:*' verbose yes
zstyle ':completion:*' completer _expand _complete _match _prefix _approximate _list _history
zstyle ':completion:*:messages' format '%F{YELLOW}%d'$DEFAULT
zstyle ':completion:*:warnings' format '%F{RED}No matches for:''%F{YELLOW} %d'$DEFAULT
zstyle ':completion:*:descriptions' format '%F{yellow}Completing %B%d%b%f'$DEFAULT
zstyle ':completion:*:options' description 'yes'

# マッチ種別を別々に表示
zstyle ':completion:*' group-name ''

########################################
# オプション (履歴まわりは home-manager 側で設定)

# 日本語ファイル名を表示可能にする
setopt print_eight_bit

# beep を無効にする
setopt no_beep

# フローコントロールを無効にする
setopt no_flow_control

# Ctrl+Dでzshを終了しない
setopt ignore_eof

# '#' 以降をコメントとして扱う
setopt interactive_comments

# ディレクトリ名だけでcdする
setopt auto_cd

# cd したら自動的にpushdする
setopt auto_pushd

# 重複したディレクトリを追加しない
setopt pushd_ignore_dups

# ヒストリに保存するときに余分なスペースを削除する
setopt hist_reduce_blanks

# 高機能なワイルドカード展開を使用する
setopt extended_glob

########################################
# エイリアス

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias mkdir='mkdir -p'

# sudo の後のコマンドでエイリアスを有効にする
alias sudo='sudo '

# OS 別の設定
case ${OSTYPE} in
    darwin*)
        # Mac用の設定
        export CLICOLOR=1
        alias ls='ls -G -F'
        ;;
    linux*)
        # Linux用の設定
        alias ls='ls -F --color=auto'
        ;;
esac

# eza / bat があれば置き換える
if command -v eza >/dev/null 2>&1; then
  alias e='eza --icons'
  alias l='eza --icons'
  alias ls='eza --icons'
  alias ea='eza -a --icons'
  alias la='eza -a --icons'
  alias ll='eza -l --icons'
else
  alias la='ls -a'
  alias ll='ls -l'
fi

if command -v bat >/dev/null 2>&1; then
  alias cat='bat'
fi

# グローバルエイリアス (パイプ用)
alias -g L='| less'
alias -g G='| grep'

# C で標準出力をクリップボードにコピーする
# mollifier delta blog : http://mollifier.hatenablog.com/entry/20100317/p1
if command -v pbcopy >/dev/null 2>&1 ; then
    # Mac
    alias -g C='| pbcopy'
elif command -v xsel >/dev/null 2>&1 ; then
    # Linux
    alias -g C='| xsel --input --clipboard'
elif command -v putclip >/dev/null 2>&1 ; then
    # Cygwin
    alias -g C='| putclip'
fi

# git
alias gs='git status'
alias gc='git commit'
alias gpush='git push origin HEAD'
alias gpull='git pull'
alias gmaster='git checkout master'

########################################
# 関数

# ブランチのチェックアウトをiikanjiに行う関数
gcheck() {
  # 引数が指定されていない場合は使い方を表示して終了
  if [[ -z "$1" ]]; then
    echo "Usage: gcheck <branch-name>" >&2
    return 1
  fi

  local branch_name="$1"
  local remote_branch="origin/$branch_name"

  # 1. ローカルに同名のブランチが存在するかチェック
  if [[ -n $(git branch --list "$branch_name") ]]; then
    echo "Switching to existing local branch '$branch_name'."
    git checkout "$branch_name"

  # 2. リモート (origin) に同名のブランチが存在するかチェック
  elif git rev-parse --verify --quiet "$remote_branch" >/dev/null; then
    echo "Creating new local branch '$branch_name' to track '$remote_branch'."
    git checkout --track "$remote_branch"

  # 3. ローカルにもリモートにも存在しない場合
  else
    echo "Creating new local branch '$branch_name'."
    git checkout -b "$branch_name"
  fi
}

# git rootディレクトリに移動する関数
gr() {
  local git_root
  git_root=$(git rev-parse --show-toplevel 2>/dev/null)

  if [[ $? -eq 0 ]]; then
    cd "$git_root"
  else
    echo "gr: not a git repository" >&2
    return 1
  fi
}

# ghq で管理しているリポジトリに fzf で移動する
function fzf-ghq() {
  local loc="$(ghq list | fzf --cycle)"
  if [[ -n $loc ]]; then
    local fullloc="$(ghq root)/$loc"
    BUFFER="cd ${fullloc}"
    zle accept-line
  fi
  zle clear-screen
}
zle -N fzf-ghq
bindkey '^g'  fzf-ghq

# exit - to close a tmux pane
exit() {
    if [[ -z $TMUX ]]; then
        builtin exit
        return
    fi

    panes=$(tmux list-panes | wc -l)
    wins=$(tmux list-windows | wc -l)
    count=$(($panes + $wins - 1))
    if [ $count -eq 1 ]; then
        tmux detach
    else
        builtin exit
    fi
}

########################################
# PATH まわり

# aqua
export PATH=${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH
export AQUA_GLOBAL_CONFIG=${AQUA_GLOBAL_CONFIG:-}:${XDG_CONFIG_HOME:-$HOME/.config}/aquaproj-aqua/aqua.yaml
if command -v aqua >/dev/null 2>&1; then
  export PATH="$(aqua root-dir)/bin:$PATH"
fi

# aqua with Node.js
export NPM_CONFIG_PREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/npm-global"
export PATH=$NPM_CONFIG_PREFIX/bin:$PATH

# マシン固有・非公開の設定は ~/.zshrc.local に置く
if [[ -f "$HOME/.zshrc.local" ]]; then
    source "$HOME/.zshrc.local"
fi

# vim:set ft=zsh:
