name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: Songmu/tagpr@0c4eb5a3b0862693702acea436a7c68bd586530d # v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
